# Generated by Django 4.1.6 on 2023-02-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lanuage',
            new_name='Language',
        ),
    ]
