# Generated by Django 4.1.6 on 2023-02-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_question_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='option',
        ),
    ]
