# Generated by Django 4.1.6 on 2023-02-08 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_testpaper_time_alter_testpaper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
