# Generated by Django 4.1.6 on 2023-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_option_question_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
