# Generated by Django 4.1.6 on 2023-02-14 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_alter_testpaper_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
