# Generated by Django 4.1.6 on 2023-02-15 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0014_testpaper_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='user',
        ),
        migrations.CreateModel(
            name='TestpaperAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('testpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
