# Generated by Django 4.1.6 on 2023-02-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_testpaperassign_end_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='language',
            new_name='course',
        ),
    ]
